export const FAIL = 'FAIL';
export const LOADED = 'LOADED';

/* AUTH ACTIONS */
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

/* CHARACTER CREATION ACTIONS */
export const CREATE_CHAR_INIT = 'CREATE_CHAR_INIT';
export const CREATE_CHAR_SEND = 'CREATE_CHAR_SEND';
export const CREATE_CHAR_SUCCESS = 'CREATE_CHAR_SUCCESS';
export const FETCH_PERKS_SUCCESS = 'FETCH_PERKS_SUCCESS';

/* CHARACTER UPDATE ACTIONS */
export const FETCH_CHARACTER_INIT = 'FETCH_CHARACTER_INIT';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_FAIL = 'FETCH_CHARACTER_FAIL';
export const MODIFY_GOLD = 'MODIFY_GOLD';
export const MODIFY_XP = 'MODIFY_XP';
export const ADD_ITEM = 'ADD_ITEM';
export const CHECK_PERK = 'CHECK_PERK';
export const SAVE_CHANGES_INIT = 'SAVE_CHANGES_INIT';
export const SAVE_CHANGES_SUCCESS = 'SAVE_CHANGES_SUCCESS';